language: cpp
compiler:
  - g++
  
before_install:
  # we need a recent version of CMake
  # - sudo add-apt-repository -y ppa:andykimpe/cmake3
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then wget --no-check-certificate https://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.tar.gz; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then tar -xzvf cmake-3.2.3-Linux-x86_64.tar.gz; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export PATH=$PWD/cmake-3.2.3-Linux-x86_64/bin:$PATH; fi
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - gcc-4.9
      - g++-4.9
      - libboost1.55-all-dev
      - cmake
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi
script: mkdir build && cd build && cmake .. && make VERBOSE=1 && cd ..
after_success:
  - bash <(curl -s https://codecov.io/bash)
