language: cpp
compiler:
  - g++
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - gcc-4.9
      - g++-4.9
      - libboost1.55-all-dev
      - cmake
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi
script: mkdir build && cd build && cmake .. && make VERBOSE=1 && cd ..
